# Generated by Django 5.1.2 on 2024-10-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrera',
        ),
    ]
